name: my first workflow
on: push

jobs:
  first_job:
    runs_ons: ubuntu-latest
    steps:
    - name: welcome message 
      run: echo "my first github action job"

    - name: list files
      run: ls -l

    - name: read files
      run: cat README.md