name: generate ascii artwork

on:
    push

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v5
        - name: check the repo files
          run: ls -ltra
        - name: Execute the shell script
          run: |
             chmod +x generate-ascii.sh
             ./generate-ascii.sh